version: 0.2

phases:
  install:
    commands:
      - echo "Installing Terraform..."
      - curl -O https://releases.hashicorp.com/terraform/1.5.0/terraform_1.5.0_linux_amd64.zip
      - unzip terraform_1.5.0_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform version
  build:
    commands:
      - echo "Running terraform init, plan, and apply..."
      - terraform init
      - terraform plan
      - terraform apply -auto-approve
